COMPONENT=DemoAppC
CFLAGS += -I$(HOME)/tinyos-main/tos/lib/printf \
	  -I$(HOME)/tinyos-main/tos/lib/net \
	  -I$(HOME)/tinyos-main/tos/lib/net/drip \
	  -I$(HOME)/tinyos-main/tos/lib/net/ctp \
	  -I$(HOME)/tinyos-main/tos/lib/net/le \
	  -DLOW_POWER_LISTENING

TINYOS_ROOT_DIR?=../../..
include $(TINYOS_ROOT_DIR)/Makefile.include

